packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/*'
  # exclude packages that are inside test/ directories
  - '!**/test/**'
  - packages/@lazy-assert/*
  - packages/@bluelovers/*

# publicHoistPattern:
#   - "ts-type"
#   - "@bluelovers/tsconfig"
#   - "@bluelovers/jest-config"
#   - "@types/node"
#   - "@types/jest"
#   - "jest"
#   - "ts-jest"
#   - "ts-node"
#   - "tsx"
#   - "tslib"

linkWorkspacePackages: true
saveWorkspaceProtocol: false
preferWorkspacePackages: true

# ignoreWorkspaceRootCheck: true

# onlyBuiltDependencies: []
# ignoredBuiltDependencies: []
minimumReleaseAgeExclude:
  - crlf-normalize@1.0.25
allowBuilds:
  '@parcel/watcher': true
  unrs-resolver: true
